version: '3.8'

services:
  configserver:
    image: aloksachan/config-server:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - eazybank

     
  accounts:
    image: aloksachan/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - eazybank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s  
    environment:
        SPRING_PROFILES_ACTIVE: dev
        SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/


  loans:
    image: aloksachan/loans-service:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - eazybank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s  
    environment:
        SPRING_PROFILES_ACTIVE: dev
        SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  cards:
    image: aloksachan/cards-service:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - eazybank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s  
    environment:
        SPRING_PROFILES_ACTIVE: dev
        SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
 
   
networks:
  eazybank-network:
   